spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3300/mysql_test_db?profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: wnsah12
  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      use-new-id-generator-mappings: true
      ddl-auto: update
    properties:
      hibernate:
        check_nullability: true
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false

springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.querydsl

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/querydsl.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
#      SQL: debug
#      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: 8989